import { defineConfig, globalIgnores } from "eslint/config";
import typescriptEslint from "@typescript-eslint/eslint-plugin";
import tsParser from "@typescript-eslint/parser";
import importPlugin from "eslint-plugin-import";
import stylistic from '@stylistic/eslint-plugin'

export default defineConfig([globalIgnores(["**/dist"]), {
    files: ["**/*.ts"],

    plugins: {
        "@typescript-eslint": typescriptEslint,
        "import": importPlugin,
        "stylistic": stylistic
    },

    languageOptions: {
        parser: tsParser,
    },

    settings: {
        "import/extensions": [".ts"]
    },

    rules: {
        "array-callback-return": "error",
        "arrow-body-style": ["error", "as-needed"],
        "dot-notation": "error",
        "eqeqeq": ["error", "always", { null: "ignore" }],
        "for-direction": "error",
        "max-depth": ["error", 4],
        "no-async-promise-executor": "error",
        "no-cond-assign": "error",
        "no-constant-condition": ["error", { checkLoops: false }],
        "no-dupe-else-if": "error",
        "no-duplicate-case": "error",
        "no-empty": ["error", { allowEmptyCatch: true }],
        "no-empty-character-class": "error",
        "no-fallthrough": "error",
        "no-inner-declarations": ["error", "functions", { blockScopedFunctions: "disallow" }],
        "no-invalid-regexp": "error",
        "no-irregular-whitespace": "error",
        "no-loss-of-precision": "error",
        "no-misleading-character-class": "error",
        "no-prototype-builtins": "error",
        "no-regex-spaces": "error",
        "no-shadow-restricted-names": "error",
        "no-sparse-arrays": "error",
        "no-unneeded-ternary": ["error", { defaultAssignment: false }],
        "no-unexpected-multiline": "error",
        "no-unsafe-optional-chaining": "error",
        "no-useless-backreference": "error",
        "no-useless-computed-key": "error",
        "no-useless-escape": "error",
        "no-restricted-globals": "error",
        "operator-assignment": ["error", "always"],
        "prefer-const": "error",
        "prefer-destructuring": ["error", { object: true, array: false }],
        "prefer-spread": "error",
        "use-isnan": "error",
        "yoda": "error",

        "@typescript-eslint/adjacent-overload-signatures": "error",
        "@typescript-eslint/array-type": "error",
        "@typescript-eslint/ban-ts-comment": "error",
        "@typescript-eslint/consistent-indexed-object-style": "error",
        // "@typescript-eslint/consistent-type-assertions": ["error", { assertionStyle: 'as', objectLiteralTypeAssertions: 'allow-as-parameter' }],
        "@typescript-eslint/consistent-type-definitions": "error",
        "@typescript-eslint/consistent-type-imports": "error",
        "@typescript-eslint/default-param-last": "error",
        "@typescript-eslint/method-signature-style": ["error", "property"],
        "@typescript-eslint/no-confusing-non-null-assertion": "error",
        "@typescript-eslint/no-duplicate-enum-values": "error",
        "@typescript-eslint/no-empty-object-type": "error",
        "@typescript-eslint/no-non-null-asserted-nullish-coalescing": "error",
        "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
        "@typescript-eslint/no-this-alias": "error",
        "@typescript-eslint/no-unnecessary-type-constraint": "error",
        "@typescript-eslint/no-unsafe-declaration-merging": "error",
        "@typescript-eslint/no-unused-expressions": "error",
        "@typescript-eslint/no-unused-vars": ["error", {
            args: "all",
            argsIgnorePattern: "^_",
            caughtErrors: "none",
            destructuredArrayIgnorePattern: "^_"
        }],
        "@typescript-eslint/prefer-as-const": "error",
        "@typescript-eslint/prefer-for-of": "error",
        "@typescript-eslint/prefer-function-type": "error",

        "import/consistent-type-specifier-style": ["error", "prefer-top-level"],
        "import/default": "error",
        "import/export": "error",
        "import/extensions": ["error", "ignorePackages"],
        "import/first": "error",
        "import/named": "error",
        "import/no-duplicates": "error",
        "import/no-empty-named-blocks": "error",
        "import/no-mutable-exports": "error",
        "import/no-self-import": "error",
        "import/no-unresolved": ["error"],
        "import/no-unused-modules": "error",
        "import/order": "error",

        "stylistic/array-bracket-spacing": ["error"],
        "stylistic/arrow-parens": ["error", "as-needed"],
        "stylistic/arrow-spacing": ["error"],
        "stylistic/block-spacing": ["error", "always"],
        "stylistic/brace-style": ["error", "1tbs", { allowSingleLine: true }],
        "stylistic/comma-spacing": ["error"],
        "stylistic/dot-location": ["error", "property"],
        "stylistic/eol-last": ["error", "always"],
        "stylistic/function-call-spacing": ["error", "never"],
        "stylistic/function-paren-newline": ["error", "consistent"],
        "stylistic/indent": ["error", 4, { SwitchCase: 1 }],
        "stylistic/indent-binary-ops": ["error", 4],
        "stylistic/key-spacing": ["error", { "mode": "strict" }],
        "stylistic/keyword-spacing": ["error"],
        "stylistic/linebreak-style": ["error", "unix"],
        "stylistic/max-len": ["error", {
            code: 120,
            ignoreStrings: true,
            ignoreRegExpLiterals: true
        }],
        "stylistic/max-statements-per-line": ["error", { max: 2 }],
        "stylistic/member-delimiter-style": "error",
        "stylistic/newline-per-chained-call": ["error", { ignoreChainWithDepth: 3 }],
        "stylistic/no-extra-parens": ["error", "all", {
            nestedBinaryExpressions: false
        }],
        "stylistic/no-extra-semi": "error",
        "stylistic/no-mixed-operators": ["error", {
            groups: [
                ["&", "|", "^", "~", "<<", ">>", ">>>"],
                ["==", "!=", "===", "!==", ">", ">=", "<", "<="],
                ["&&", "||"],
                ["in", "instanceof"]
            ]
        }],
        "stylistic/no-mixed-spaces-and-tabs": "error",
        "stylistic/no-multi-spaces": "error",
        "stylistic/no-trailing-spaces": "error",
        "stylistic/no-whitespace-before-property": "error",
        "stylistic/object-curly-spacing": ["error", "always"],
        "stylistic/operator-linebreak": ["error", "before", { overrides: { "=": "after" } }],
        "stylistic/quote-props": ["error", "consistent-as-needed"],
        "stylistic/quotes": ["error", "double", { avoidEscape: true }],
        "stylistic/rest-spread-spacing": ["error"],
        "stylistic/semi": ["error", "always"],
        "stylistic/semi-spacing": ["error"],
        "stylistic/space-in-parens": ["error", "never"],
        "stylistic/space-infix-ops": "error",
        "stylistic/space-unary-ops": "error",
        "stylistic/spaced-comment": ["error", "always", { markers: ["!"] }],
        "stylistic/switch-colon-spacing": ["error"],
        "stylistic/template-curly-spacing": ["error", "never"],
        "stylistic/type-annotation-spacing": ["error"],
        "stylistic/type-generic-spacing": ["error"],
        "stylistic/wrap-iife": ["error", "inside"],
    },
}]);
